# Generated by Django 3.0.7 on 2020-06-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sender', 'Sender'), ('accepted', 'Accepted')], max_length=8),
        ),
    ]
