# Generated by Django 3.0.7 on 2020-06-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200701_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
    ]
