# Generated by Django 2.2.8 on 2020-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs/%Y/%m/%d', verbose_name='file name')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='uploaded')),
                ('activated', models.BooleanField(default=False, verbose_name='activated')),
            ],
        ),
    ]
