# Generated by Django 2.2.8 on 2020-07-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='csv',
            name='file_name',
            field=models.FileField(upload_to='csvs/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
