# Generated by Django 2.2.8 on 2020-07-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Author'),
        ),
    ]
