# Generated by Django 2.2.8 on 2020-07-06 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200706_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='name',
            new_name='salesman',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
